In [65]:
# source "C:/Users/leand/venvs/pns/Scripts/activate"
# python -m ipykernel install --user --name=pns --display-name "pns"

import os
import pandas as pd
import seaborn as sns

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import os
from tqdm import tqdm

pd.set_option('display.max_columns', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_seq_items', None)   # ou um inteiro grande, ex: 1000

# Analise de Dados

In [66]:
modulo_identificacao = [
    # Módulo de Identificacao
    "V0001",  # Unidade da Federação
    "V0024", # Estrato
    "UPA_PNS", # UPA
    "V0006_PNS", # Número ordem domicilio PNS
    "C00301", # Número ordem do morador
    "V0015", # Tipo da Entrevista
    "V0022", # Quantidade de moradores
    "V0026",  # Tipo de situação censitária
    "V0031", # Tipo de área Capital, Metropolitana
    "V0025A", # Seleção do morador de 15 anos ou mais para responder o questionário individual
    "V0025B", # Seleção do morador de 15 anos ou mais para ter medida antropométrica aferida
    "V0029", # Peso amostral do morador sem calibração
    "V00291", # Peso amostral do morador com calibração
    "V00282", #		Projeção da população
    "V00283", #	Domínio de projeção para domicílio e moradores
    "V00293", # Domínio de projeção para morador selecionado
    "V00303", # Domínio de projeção para morador selecionado para antropometria
    "VDF003", # Rendimento mensal domiciliar per capita
    ]
modulo_C = [
    # Módulo C - Caracteristicas gerais dos moradores
    "C001", # Quantidade de pessoas no domicilio
    "C006",  # Sexo
    "C00701",  # Dia de nascimento
    "C00702",  # Mês de nascimento
    "C00703",  # Ano de nascimento
    "C008",  # Idade do morador na data de referência
    "C009",  # Cor ou Raça
    "C011",  # Estado civil
]
modulo_D = [
    # Módulo D - Cartacterisiticas de Educação dos Moradores
    "D00201",  # Frequenta escola ou creche
    "D00901",  # Qual foi o curso mais elevado que ___frequentou
]
modulo_E = [
    # Módulo E - Características de Trabalho
    "E01602",  # Qual era o rendimento bruto mensal ou retirada que ___ fazia normalmente nesse trabalho?(valor em dinheiro)
    "E017", # Quantas horas ___ trabalhava normalmente, por semana, nesse trabalho?
]
modulo_G = [
    # Módulo G - Deficiecias maiores de 2 anos
    "G033",  # ___ usa óculos ou outro aparelho de auxílio para lidar com problemas de visão?
    "G047",  #  ___ tem dificuldade permanente de enxergar?
    "G046",  # ___ tem dificuldade permanente de enxergar mesmo usando óculos, lentes de contato ou lupas?
    "G049",  # ____________ faz uso de aparelho auditivo
    "G051",  # ____________ faz uso de implante coclear?
    "G053",  # ____________ faz uso de sistema de frequência modulada individual (sistema FM)?
    "G059",  # ___ usa algum aparelho de auxílio para se locomover?
    "G060",  # ____________ faz uso de cadeira de rodas?
    "G062",  # ____________ faz uso de bengala, muletas ou andador?
    "G064",  # ____________ faz uso de prótese?
    "G066",  # ____________ faz uso de órtese?
    "G070",  # ___ tem dificuldade permanente de caminhar ou subir degraus, mesmo usando prótese, bengala ou outro aparelho de auxílio? (Para moradores com 5 anos ou mais de idade.) OU Comparado com crianças da mesma idade, ___ tem dificuldade permanente para caminhar, mesmo usando prótese, bengala ou aparelho de auxílio? (Para moradores com 2 a 4 anos de idade.)
    "G072",  # ___ usa algum aparelho de auxílio para realizar movimentos com os membros superiores?
    "G073",  # ____________ faz uso de prótese para os membros superiores?
    "G079",  #  ___tem dificuldade permanente para levantar uma garrafa com dois litros de água da cintura até a altura dos olhos, mesmo usando prótese ou aparelho de auxílio? (Somente para moradores com 5 anos ou mais de idade.)
    "G083",  # Por causa de alguma limitação nas funções mentais ou intelectuais, _________ tem dificuldade permanente para realizar atividades habituais, como se comunicar, realizar cuidados pessoais, trabalhar, ir à escola, brincar, etc.? (Para moradores com 5 anos ou mais de idade.) OU Por causa de alguma limitação nas funções mentais ou intelectuais, _________ tem dificuldade permanente para realizar atividades habituais, como frequentar a escola, brincar e etc.? (Para moradores com 2 a 4 anos de idade.)
    "G084",  # Nos últimos doze meses ___ recebe ou recebeu, algum cuidado em reabilitação de forma regular? (Por reabilitação quero dizer fisioterapia, terapia ocupacional, fonoaudiologia psicoterapia etc.)
]

modulo_J =  [
    # Utilização de Serviços de saude
    'J001', # estado de saude
    'J007', # doença cronica
    'J012', # Quantidade de consultas médicas no ultimos 12 meses
    "J00402", #  Qual foi o principal motivo de saúde que impediu ___ de realizar suas atividades habituais nas duas últimas semanas
]

modulo_L = [
    # Módulo L - Crianças com menos de dois anos
    "L019",  # Alguma vez ___________ recebeu Sulfato Ferroso?
    "L021",  # Foi realizado o teste do pezinho?
    "L033",  # O teste do coraçãozinho realizado deu resultado alterado?
    "L037",  # Vacina Penta (também chamada de Pentavalente, DTP/Hib/HB)
    "L038",  # Vacina Poliomielite (também chamada de gotinha, VIP, VOP, PÓLIO, ANTIPÓLIO, POLIOMIELITE, SABIN)
    "L039",  # Vacina Pneumocócica (também chamada de Pneumo 10, Pneumo 13, Pncc)
    "L040",  # Vacina Tríplice Viral (também chamada SCR, TRIVIRAL, TV, MMR).
    "L01701",  # Leite materno?
    "L018",  # Desde que ___________nasceu, tomou ou comeu outro alimento que não leite materno?
    "L019",  # Alguma vez ___________ recebeu Sulfato Ferroso?
]
modulo_P = [
    # Módulo P - Estilos de Vida
    "P00103",  # Peso - Informado (em kg) (3 inteiros e 1 casa decimal)
    "P00104",  # Peso - Final (em kg) (3 inteiros e 1 casa decimal)
    "P00403",  # Altura - Informada (em cm) (3 inteiros)
    "P00404",  # Altura - Final (em cm) (3 inteiros)
    "P027",    # Com que frequência o(a) Sr(a) costuma consumir alguma bebida alcoólica?
    "P034", # atividade fisica
    "P035",    # Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte?
    "P050", # Atualmente, o(a) Sr(a) fuma algum produto do tabaco?
    "P052", # E no passado, o(a) Sr(a) fumou algum produto do tabaco?
]
modulo_Q = [
    # Módulo Q - Doenças crônicas
    "Q00201",  # Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)?
    "Q00202",  # Essa hipertensão arterial (pressão alta) ocorreu apenas durante algum período de gravidez?
    "Q003",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de hipertensão arterial (pressão alta)?
    "Q028",  # Em geral, em que grau a hipertensão ou alguma complicação da hipertensão limita as suas atividades habituais (como trabalhar, estudar, realizar afazeres domésticos etc.)?
    "Q03001",  # Algum médico já lhe deu o diagnóstico de diabetes?
    "Q03002",  # Esse diabetes ocorreu apenas durante algum período de gravidez?
    "Q031",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico do diabetes?
    "Q055011",  # Problemas na vista
    "Q055012",  # Infarto ou AVC (Acidente Vascular cerebral) /derrame ou outro problema circulatório
    "Q055013",  # Problema nos rins
    "Q060",  # Algum médico já lhe deu o diagnóstico de colesterol alto?
    "Q061",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de colesterol alto?
    "Q06306", # um médico já lhe deu o diagnóstico de uma doença do coração, tal como infarto, angina, insuficiência cardíaca ou outra?
    "Q06307",  # Infarto
    "Q06308",  # Angina
    "Q06309",  # Insuficiência cardíaca
    "Q06310",  # Arritmia
    "Q064",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico da doença do coração?
    "Q068",  # Algum médico já lhe deu o diagnóstico de AVC (Acidente Vascular Cerebral) ou derrame?
    "Q070",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico do derrame (ou AVC)?
    "Q074",  # Algum médico já lhe deu o diagnóstico de asma (ou bronquite asmática)?
    "Q075",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de asma?
    "Q079",  # Algum médico já lhe deu o diagnóstico de artrite ou reumatismo?
    "Q080",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de artrite ou reumatismo?
    "Q084",  # O(a) Sr(a) tem algum problema crônico de coluna, como dor crônica nas costas ou no pescoço, lombalgia, dor ciática, problemas nas vértebras ou disco?
    "Q085",  # Que idade o(a) Sr(a) tinha quando começou o problema na coluna?
    "Q087",  # Em geral, em que grau o problema na coluna limita as suas atividades habituais (tais como trabalhar, realizar afazeres domésticos, etc.)?
    "Q088",  # Algum médico já lhe deu o diagnóstico de DORT?
    "Q08901",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de DORT?
    "Q091",  # Em geral, em que grau o DORT limita as suas atividades habituais (tais como trabalhar, realizar afazeres domésticos etc.)?
    "Q092",  # Algum médico ou profissional de saúde mental (como psiquiatra ou psicólogo) já lhe deu o diagnóstico de depressão?
    "Q09301",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de depressão?
    "Q109",  # Em geral, em que grau a depressão limita as suas atividades habituais (tais como trabalhar, realizar afazeres domésticos, etc.)?
    "Q11006", #Algum médico ou profissional de saúde (como psiquiatra ou psicólogo) já lhe deu o diagnóstico de outra doença mental, como transtorno de ansiedade, síndrome do pânico, esquizofrenia, transtorno bipolar, psicose ou TOC (Transtorno Obsessivo Compulsivo) etc?
    "Q11007",  # Diagnóstico de Esquizofrenia
    "Q11008",  # Diagnóstico de Transtorno bipolar
    "Q11009",  # Diagnóstico de TOC (Transtorno obsessivo compulsivo)
    "Q111",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de doença mental?
    "Q11604",  # Algum médico já lhe deu o diagnóstico de alguma outra doença crônica no pulmão, tais como enfisema pulmonar, bronquite crônica ou DPOC (Doença Pulmonar Obstrutiva Crônica)?
    "Q11605",  # Diagnóstico de enfisema pulmonar
    "Q11606",  # Diagnóstico de bronquite crônica
    "Q11701",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico dessa(s) doença(s) no pulmão?
    "Q120",  # Algum médico já lhe deu diagnóstico de câncer?
    "Q12201",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de doença mental?
    "Q124",  # Algum médico já lhe deu o diagnóstico de insuficiência renal crônica?
    "Q125",  # Que idade o(a) Sr(a) tinha no primeiro diagnóstico de insuficiência renal crônica?
    "Q128", # Algum médico já lhe deu algum diagnóstico de outra doença crônica (física ou mental) ou doença de longa duração (de mais de 6 meses de duração)?
]
modulo_R = [
    # Módculo R - Saúde da Mulher - 15 anos ou mais
    "R011", # Segundo o médico, qual o motivo da retirada do útero?
    "R025",  # Com que idade a sra ficou menstruada pela primeira vez?
    "R026",  # A sra ainda fica menstruada?
    "R027",  # Com que idade a sra parou de menstruar?
    "R028",  # A sra já entrou na menopausa?
    "R029",  # Alguma vez a sra fez ou faz tratamento hormonal para alívio dos sintomas da menopausa (com comprimidos, adesivos, gel ou injeções)?
    "R034",  # A sra usa algum método para evitar a gravidez atualmente?
    "R035",  # Qual o principal motivo de não evitar a gravidez?
    "R03601",  # Pilula?
    "R037",  # A sra e/ou seu companheiro já fizeram ou fazem algum tratamento para engravidar?
    "R038",  # Há quanto tempo a sra está tentando engravidar?
    
]
modulo_S = [
    # Módulo S - Atendimento pré-natal e parto - 15 anos ou mais
    "S065",  # Alguma vez ficou grávida, mesmo que a gravidez não tenha chegado até o final?
    "S066",  # Quantos partos a Sra já teve?
    "S06703",  # Em que data foi o último parto? ANO
    "S068",  # Quando estava grávida fez alguma consulta de pré-natal?
    "S06901",  # Quantas tempo de gravidez tinha quando fez a primeira consulta pré-natal?
    "S06902",  # Quantas tempo de gravidez tinha quando fez a primeira consulta pré-natal?
    "S070",  # Quantas consultas de pré-natal fez durante esta gravidez?
    "S076",    # Realização de exames de sangue durante o pré-natal
    "S077",    # Realização de exames de urina durante o pré-natal
    "S090",    # Teste de HIV realizado durante o pré-natal
    "S080",  # Durante o pré-natal de ______, foi realizado teste/exame para sífilis?
    "S082",  # Qual foi o resultado do teste/exame para sífilis?
    "S083",  # Recebeu tratamento para sífilis?
    "S086",  # Qual foi o resultado do teste/exame para sífilis do seu parceiro?
    "S087",  # O seu parceiro foi tratado?
    "S095",  # Durante o pré-natal a Sra foi orientada a usar preservativo?
    "S096",  # Quanto tempo antes do parto a Sra foi à última consulta do pré-natal?
    "S098",  # Quando estava grávida tomou alguma injeção para prevenir o bebê contra difteria e tétano (mal dos sete dias) – dT ou dTpa?
    "S099",  # Quantas doses dessa injeção tomou durante esta gravidez?
    "S09901",  # Número de doses
    "S110",  # Qual foi o peso dele(a) ao nascer?
    "S11001",  # Peso ao nascer (em quilogramas)
    "S112",  # Onde foi realizado o parto?
    "S115",  # Qual foi o tipo de parto?
    "S116",  # Nesta gravidez, entrou em trabalho de parto?
    "S117",  # Qual o principal motivo de ter tido parto cesáreo?
    "S118",  # Quantas semanas de gravidez tinha no momento do parto?
    "S11801",  # Quantidade de semanas
    "S125",  # Teve alguma complicação durante o parto?
    "S126",  # Você teve alguma complicação após o parto?
    "S127",  # Por causa dessa complicação precisou ser internada?
    "S130",  # Durante a primeira hora após o nascimento, seu(sua) filho(a) foi colocado(a) em contato com você pele a pele?
    "S131",  # Depois do nascimento, ele(a) ficou com você no quarto até a alta hospitalar?
    "S132",  # Seu(sua) filho(a) saiu do hospital junto com você?
    "S133",  # A criança não saiu do hospital junto com você porque:
    "S134",  # Você fez consulta de puerpério (consulta com médico ou enfermeiro até 42 dias após o parto)?
    "S136",  # Durante os primeiros três meses após o parto, você tomou medicamento contendo somente ferro ou ferro com vitaminas?
]




modulo_T = [
    # Módulo de DST
    "T004", #Nos últimos 12 meses, algum médico lhe deu diagnóstico de doença/infecção sexualmente transmissível?

]
modulo_W = [
    # Módulo W - Antropometria
    "W001",  # Antropometria aferida do morador selecionado
    "W00101",  # Peso - 1ª pesagem (em kg)(3 inteiros e 1 casa decimal)
    "W00102",  # Peso - 2ª pesagem (em kg)(3 inteiros e 1 casa decimal)
    "W00103",  # Peso - Final (em kg)(3 inteiros e 1 casa decimal)
    "W00201",  # Altura - 1ª medição (em cm)(3 inteiros e 1 casa decimal)
    "W00202",  # Altura - 2ª medição (em cm)(3 inteiros e 1 casa decimal)
    "W00203",  # Altura - Final (em cm)(3 inteiros e 1 casa decimal)
    "VDL001",  # Idade em meses das crianças nascidas no período de referência do Módulo L
]

modulo_derivadas = [
    "VDE014", #Grupamentos de atividade do trabalho principal da semana de referência para pessoas de 14 anos ou mais de idade
    "VDF004", # Faixa de rendimento domiciliar per capita (exclusive o rendimento das pessoas cuja condição na unidade domiciliar era pensionista, empregado doméstico ou parente do
]

In [67]:
colunas_interesse = modulo_identificacao + modulo_C + modulo_D + modulo_E + modulo_G + modulo_J + modulo_L + modulo_P + modulo_Q + modulo_R + modulo_S + modulo_T + modulo_W + modulo_derivadas

In [68]:
pns_2019 = pd.read_csv("data/2019/pns2019.csv", delimiter=',', low_memory=False, usecols=colunas_interesse,)
pns_2019

,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0022,V0026,V0031,V0025A,V0025B,C001,C00301,C006,C00701,C00702,C00703,C008,C009,C011,D00201,D00901,E01602,E017,G033,G046,G047,G049,G051,G053,G059,G060,G062,G064,G066,G070,G072,G073,G079,G083,G084,J001,J00402,J007,J012,L01701,L018,L019,L021,L033,L037,L038,L039,L040,P00103,P00104,P00403,P00404,P027,P034,P035,P050,P052,Q00201,Q00202,Q003,Q028,Q03001,Q03002,Q031,Q055011,Q055012,Q055013,Q060,Q061,Q06306,Q06307,Q06308,Q06309,Q06310,Q064,Q068,Q070,Q074,Q075,Q079,Q080,Q084,Q085,Q087,Q088,Q08901,Q091,Q092,Q09301,Q109,Q11006,Q11007,Q11008,Q11009,Q111,Q11604,Q11605,Q11606,Q11701,Q120,Q12201,Q124,Q125,Q128,R011,R025,R026,R027,R028,R029,R034,R035,R03601,R037,R038,S065,S066,S06703,S068,S06901,S06902,S070,S076,S077,S080,S082,S083,S086,S087,S090,S095,S096,S098,S099,S09901,S110,S11001,S112,S115,S116,S117,S118,S11801,S125,S126,S127,S130,S131,S132,S133,S134,S136,T004,W001,W00101,W00102,W00103,W00201,W00202,W00203,V0029,V00291,V00282,V00283,V00293,V00303,VDE014,VDF003,VDF004,VDL001
0,11,1110011,110000016,1,1,6.0,1,1,1.0,NaN,6.0,1.0,2.0,22.0,11.0,1963.0,55.0,1.0,1.0,2.0,5.0,100.0,40.0,2.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,3.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,60.0,145.0,145.0,2.0,1.0,1.0,3.0,1.0,1.0,2.0,46.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,55.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,1.0,45.0,1.0,50.0,1.0,2.0,NaN,NaN,1.0,50.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,12.0,2.0,45.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,4.0,1987.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.767254,368.875166,529479.0,111.0,11124.0,NaN,6.0,350.0,2.0,NaN
1,11,1110011,110000016,1,1,6.0,1,1,0.0,NaN,6.0,2.0,1.0,8.0,4.0,1950.0,69.0,4.0,1.0,2.0,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,2.0,3.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,529479.0,111.0,NaN,NaN,NaN,350.0,2.0,NaN
2,11,1110011,110000016,1,1,6.0,1,1,0.0,NaN,6.0,3.0,1.0,13.0,9.0,1987.0,31.0,2.0,4.0,2.0,10.0,1000.0,36.0,1.0,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,3.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,529479.0,111.0,NaN,NaN,4.0,350.0,2.0,NaN
3,11,1110011,110000016,1,1,6.0,1,1,9.0,NaN,6.0,4.0,1.0,99.0,99.0,9999.0,9.0,2.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,2.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,529479.0,111.0,NaN,NaN,NaN,350.0,2.0,NaN
4,11,1110011,110000016,1,1,6.0,1,1,9.0,NaN,6.0,5.0,2.0,99.0,99.0,9999.0,6.0,4.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,2.0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,529479.0,111.0,NaN,NaN,NaN,350.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293721,53,5310220,530044434,14,1,4.0,2,1,0.0,NaN,4.0,1.0,2.0,26.0,4.0,1970.0,49.0,2.0,4.0,2.0,10.0,2000.0,56.0,1.0,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,NaN,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3015156.0,531.0,NaN,NaN,1.0,3348.0,6.0,NaN
293722,53,5310220,530044434,14,1,4.0,2,1,1.0,NaN,4.0,2.0,1.0,12.0,2.0,1935.0,84.0,4.0,3.0,2.0,14.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,NaN,2.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3015156.0,531.0,NaN,NaN,NaN,3348.0,6.0,NaN
293723,53,5310220,530044434,14,1,4.0,2,1,0.0,NaN,4.0,3.0,1.0,16.0,10.0,1997.0,21.0,1.0,4.0,1.0,NaN,990.0,20.0,2.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3015156.0,531.0,NaN,NaN,7.0,3348.0,6.0,NaN
293724,53,5310220,530044434,14,1,4.0,2,1,9.0,NaN,4.0,4.0,2.0,25.0,5.0,2006.0,13.0,4.0,4.0,1.0,NaN,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3015156.0,531.0,NaN,NaN,NaN,3348.0,6.0,NaN
293725,53,5310220,530044434,15,8,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df_copy = pns_2019.copy()

In [70]:
# Armazenar em um unico Dataframe
pns_2019 = df_copy.copy()
pns_2019.info(show_counts=True, verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293726 entries, 0 to 293725
Data columns (total 175 columns):
 #    Column     Non-Null Count   Dtype
---   ------     --------------   -----
 0    V0001      293726 non-null  int64
 1    V0024      293726 non-null  int64
 2    UPA_PNS    293726 non-null  int64
 3    V0006_PNS  293726 non-null  int64
 4    V0015      293726 non-null  int64
 5    V0022      279382 non-null  float64
 6    V0026      293726 non-null  int64
 7    V0031      293726 non-null  int64
 8    V0025A     279382 non-null  float64
 9    V0025B     20712 non-null   float64
 10   C001       279382 non-null  float64
 11   C00301     279382 non-null  float64
 12   C006       279382 non-null  float64
 13   C00701     279382 non-null  float64
 14   C00702     279382 non-null  float64
 15   C00703     279382 non-null  float64
 16   C008       279382 non-null  float64
 17   C009       279382 non-null  float64
 18   C011       242444 non-null  float64
 19   D00201     279382 non-null  float64
 20   D00901     178013 non-null  float64
 21   E01602     120855 non-null  float64
 22   E017       124399 non-null  float64
 23   G033       272499 non-null  float64
 24   G046       101134 non-null  float64
 25   G047       171365 non-null  float64
 26   G049       2017 non-null    float64
 27   G051       2017 non-null    float64
 28   G053       2017 non-null    float64
 29   G059       272499 non-null  float64
 30   G060       4173 non-null    float64
 31   G062       4173 non-null    float64
 32   G064       4173 non-null    float64
 33   G066       4173 non-null    float64
 34   G070       4173 non-null    float64
 35   G072       272499 non-null  float64
 36   G073       1288 non-null    float64
 37   G079       1251 non-null    float64
 38   G083       272499 non-null  float64
 39   G084       70406 non-null   float64
 40   J001       279382 non-null  float64
 41   J00402     21952 non-null   float64
 42   J007       279382 non-null  float64
 43   J012       206384 non-null  float64
 44   L01701     6632 non-null    float64
 45   L018       293 non-null     float64
 46   L019       6632 non-null    float64
 47   L021       6632 non-null    float64
 48   L033       3683 non-null    float64
 49   L037       4856 non-null    float64
 50   L038       4856 non-null    float64
 51   L039       4856 non-null    float64
 52   L040       4856 non-null    float64
 53   P00103     83073 non-null   float64
 54   P00104     89954 non-null   float64
 55   P00403     75637 non-null   float64
 56   P00404     89954 non-null   float64
 57   P027       90846 non-null   float64
 58   P034       90846 non-null   float64
 59   P035       36398 non-null   float64
 60   P050       90846 non-null   float64
 61   P052       79460 non-null   float64
 62   Q00201     88736 non-null   float64
 63   Q00202     14467 non-null   float64
 64   Q003       22574 non-null   float64
 65   Q028       22574 non-null   float64
 66   Q03001     84073 non-null   float64
 67   Q03002     4492 non-null    float64
 68   Q031       7101 non-null    float64
 69   Q055011    6326 non-null    float64
 70   Q055012    6326 non-null    float64
 71   Q055013    6326 non-null    float64
 72   Q060       82881 non-null   float64
 73   Q061       13471 non-null   float64
 74   Q06306     90846 non-null   float64
 75   Q06307     4732 non-null    float64
 76   Q06308     4732 non-null    float64
 77   Q06309     4732 non-null    float64
 78   Q06310     4732 non-null    float64
 79   Q064       4732 non-null    float64
 80   Q068       90846 non-null   float64
 81   Q070       1975 non-null    float64
 82   Q074       90846 non-null   float64
 83   Q075       4467 non-null    float64
 84   Q079       90846 non-null   float64
 85   Q080       7214 non-null    float64
 86   Q084       90846 non-null   float64
 87   Q085       19206 non-null   float64
 88   Q087       19206 non-null   float64
 89   Q088       90846 non-null   float64
 90   Q08901     1711 non-null    float64
 91   Q091       1711 non-null    float64
 92   Q092       90846 non-null   float64
 93   Q09301     8332 non-null    float64
 94   Q109       8332 non-null    float64
 95   Q11006     90846 non-null   float64
 96   Q11007     4905 non-null    float64
 97   Q11008     4905 non-null    float64
 98   Q11009     4905 non-null    float64
 99   Q111       4905 non-null    float64
 100  Q11604     90846 non-null   float64
 101  Q11605     1279 non-null    float64
 102  Q11606     1279 non-null    float64
 103  Q11701     1279 non-null    float64
 104  Q120       90846 non-null   float64
 105  Q12201     2076 non-null    float64
 106  Q124       90846 non-null   float64
 107  Q125       1287 non-null    float64
 108  Q128       90846 non-null   float64
 109  R011       4403 non-null    float64
 110  R025       48047 non-null   float64
 111  R026       43644 non-null   float64
 112  R027       17064 non-null   float64
 113  R028       17064 non-null   float64
 114  R029       16435 non-null   float64
 115  R034       21628 non-null   float64
 116  R035       8895 non-null    float64
 117  R03601     12733 non-null   float64
 118  R037       21628 non-null   float64
 119  R038       67 non-null      float64
 120  S065       48047 non-null   float64
 121  S066       37461 non-null   float64
 122  S06703     36434 non-null   float64
 123  S068       2910 non-null    float64
 124  S06901     2824 non-null    float64
 125  S06902     2824 non-null    float64
 126  S070       2824 non-null    float64
 127  S076       2824 non-null    float64
 128  S077       2824 non-null    float64
 129  S080       2824 non-null    float64
 130  S082       2158 non-null    float64
 131  S083       8 non-null       float64
 132  S086       511 non-null     float64
 133  S087       15 non-null      float64
 134  S090       2824 non-null    float64
 135  S095       2824 non-null    float64
 136  S096       2824 non-null    float64
 137  S098       2824 non-null    float64
 138  S099       1890 non-null    float64
 139  S09901     1268 non-null    float64
 140  S110       2855 non-null    float64
 141  S11001     2646 non-null    float64
 142  S112       2910 non-null    float64
 143  S115       2910 non-null    float64
 144  S116       1516 non-null    float64
 145  S117       1516 non-null    float64
 146  S118       2910 non-null    float64
 147  S11801     2619 non-null    float64
 148  S125       2910 non-null    float64
 149  S126       2910 non-null    float64
 150  S127       301 non-null     float64
 151  S130       2910 non-null    float64
 152  S131       2873 non-null    float64
 153  S132       2873 non-null    float64
 154  S133       184 non-null     float64
 155  S134       2910 non-null    float64
 156  S136       2910 non-null    float64
 157  T004       90846 non-null   float64
 158  W001       7060 non-null    float64
 159  W00101     6569 non-null    float64
 160  W00102     6569 non-null    float64
 161  W00103     6730 non-null    float64
 162  W00201     6561 non-null    float64
 163  W00202     6561 non-null    float64
 164  W00203     6730 non-null    float64
 165  V0029      90846 non-null   float64
 166  V00291     90846 non-null   float64
 167  V00282     279382 non-null  float64
 168  V00283     279382 non-null  float64
 169  V00293     90846 non-null   float64
 170  V00303     6730 non-null    float64
 171  VDE014     124399 non-null  float64
 172  VDF003     279210 non-null  float64
 173  VDF004     279210 non-null  float64
 174  VDL001     6632 non-null    float64
dtypes: float64(168), int64(7)
memory usage: 392.2 MB

In [71]:
pns_2019['chave_domicio'] = pns_2019['V0001'].astype(str) + '_' + pns_2019['V0024'].astype(str) + '_' + pns_2019['UPA_PNS'].astype(str) + '_' + pns_2019['V0006_PNS'].astype(str)
pns_2019['chave_pessoa']  = pns_2019['V0001'].astype(str) + '_' + pns_2019['V0024'].astype(str) + '_' + pns_2019['UPA_PNS'].astype(str) + '_' + pns_2019['V0006_PNS'].astype(str) + '_' + pns_2019['C00301'].astype(str)
pns_2019['V00291'] = pns_2019['V00291'].astype(str).str.replace(',', '.', regex=False).str.strip().replace('', np.nan).astype(float)
pns_2019['peso_morador_selec'] = pns_2019['V00291']*(94114 / 168426190) # alterar para população do brasil nessa data, provavel que nem precise/use essa coluna

In [72]:
df = pns_2019.copy()
# Dicionário para renomear as colunas
rename_columns = {
    "V0001": "UF",
    "V0024":"Estrato",
    "UPA_PNS":"UPA",
    "V0006_PNS":"N_ordem_domicilio_PNS",
    "C00301":"N_ordem_morador",
    "C001":"N_pessoas_domicilio",
    "V0022":"Quantidade_moradores",
    "V0015":'tipo_entrevista',
    "V0026": "regiao_metropolitana",
    "V0031": "capital_metropolitana",
    "C006": "sexo",
    "C00701": "dia_nascimento",
    "C00702": "mes_nascimento",
    "C00703": "ano_nascimento",
    "C008": "idade",
    "C011": "estado_civil",
    "P00103": "peso_info_kg",
    "P00104": "peso_final_kg",
    "P00403": "altura_info_cm",
    "P00404": "altura_final_cm",
    "W001": "antropometria_aferida_morador",
    "W00101": "peso_1_pesagem_kg",
    "W00102": "peso_2_pesagem_kg",
    "W00103": "peso_final_medido_kg",
    "W00201": "altura_1_medicao_cm",
    "W00202": "altura_2_medicao_cm",
    "W00203": "altura_final_medida_cm",
}

# Renomear as colunas no DataFrame
# df.rename(columns=rename_columns, inplace=True)

# Iterar sobre as colunas do dicionário e criar novas colunas
for original_col, new_col in rename_columns.items():
    if original_col in df.columns:  # Verificar se a coluna original existe no DataFrame
        df[new_col] = df[original_col]  # Criar a nova coluna com os mesmos valores da original

In [73]:
# Preencher a coluna de estado
estados = {
    11: "Rondônia",
    12: "Acre",
    13: "Amazonas",
    14: "Roraima",
    15: "Pará",
    16: "Amapá",
    17: "Tocantins",
    21: "Maranhão",
    22: "Piauí",
    23: "Ceará",
    24: "Rio Grande do Norte",
    25: "Paraíba",
    26: "Pernambuco",
    27: "Alagoas",
    28: "Sergipe",
    29: "Bahia",
    31: "Minas Gerais",
    32: "Espírito Santo",
    33: "Rio de Janeiro",
    35: "São Paulo",
    41: "Paraná",
    42: "Santa Catarina",
    43: "Rio Grande do Sul",
    50: "Mato Grosso do Sul",
    51: "Mato Grosso",
    52: "Goiás",
    53: "Distrito Federal",
}

df['UF_sigla'] = df['UF'].map(estados)

# Mapeamento direto de estados para suas macroregiões
estado_para_regiao = {
    "Rondônia": "Norte",
    "Acre": "Norte",
    "Amazonas": "Norte",
    "Roraima": "Norte",
    "Pará": "Norte",
    "Amapá": "Norte",
    "Tocantins": "Norte",
    "Maranhão": "Nordeste",
    "Piauí": "Nordeste",
    "Ceará": "Nordeste",
    "Rio Grande do Norte": "Nordeste",
    "Paraíba": "Nordeste",
    "Pernambuco": "Nordeste",
    "Alagoas": "Nordeste",
    "Sergipe": "Nordeste",
    "Bahia": "Nordeste",
    "Minas Gerais": "Sudeste",
    "Espírito Santo": "Sudeste",
    "Rio de Janeiro": "Sudeste",
    "São Paulo": "Sudeste",
    "Paraná": "Sul",
    "Santa Catarina": "Sul",
    "Rio Grande do Sul": "Sul",
    "Mato Grosso do Sul": "Centro-Oeste",
    "Mato Grosso": "Centro-Oeste",
    "Goiás": "Centro-Oeste",
    "Distrito Federal": "Centro-Oeste",
}

# Adicionar a coluna 'regiao_brasileira' ao DataFrame
df['regiao_brasileira'] = df['UF_sigla'].map(estado_para_regiao)

#Mapear região
regiao = {
    1: "Urbano",
    2: "Rural",
}
df['regiao_metropolitana'] = df['regiao_metropolitana'].map(regiao)

# Dicionário de mapeamento
regioes_map = {
    1: "Capital",
    2: "Região Metropolitana, excluindo a capital",
    3: "RIDE, excluindo a capital",
    4: "Interior"
}
df['capital_metropolitana'] = df['capital_metropolitana'].map(regioes_map)

# Dicionário de Sexo
sexo = {
    1: "Masculino",
    2: "Feminino"
}
df['sexo'] = df['sexo'].map(sexo)

# Pesquisa realizada
status_domicilios = {
    1: "Realizada",
    2: "Domicílio Fechado",
    3: "Recusa",
    4: "Outro Motivo",
    5: "Domicílio Vago",
    6: "Domicílio de uso ocasional",
    7: "Domicílio coletivo ou improvisado",
    8: "Domicílio em obras ou em ruínas",
    9: "Domicílio demolido",
    10: "Domicílio não encontrado",
    11: "Unidade não residencial",
    12: "Domicílio fora do setor",
}
df['tipo_entrevista'] = df['tipo_entrevista'].map(status_domicilios)

# Dicionário de mapeamento
map_raca = {
    1: 'Branca',
    2: 'Preta',
    3: 'Amarela',
    4: 'Parda',
    5: 'Indígena',
    9: 'Ignorado'
    # Se houver um código específico p/ "Não aplicável", inclua-o aqui
    # Exemplo: 99: 'Não aplicável'
}
df['raca'] = df['C009'].map(map_raca)

# Dicionário de mapeamento
map_estado_civil = {
    1: 'Casado',
    2: 'Divorciado',
    3: 'Viúvo',
    4: 'Solteiro',
    9: 'Não aplicável',
    np.nan: 'Não aplicável'

}
df['estado_civil'] = df['C011'].map(map_estado_civil)


df.shape, df.drop_duplicates().shape

((293726, 208), (293726, 208))

In [74]:
df['estado_civil'].value_counts(dropna=False)

estado_civil
Solteiro         133751
Casado            83314
Não aplicável     51282
Divorciado        12820
Viúvo             12559
Name: count, dtype: int64

# Dados não informados na pesquisa

5% - 16342 não informaram Data de nascimento

67,8% sem informação de peso e Altura

Sessão W - 2,5% dos entrevistados foram Aferidos

# Limpeza

- Somente entrevistas realizadas
- Informações de Idade

In [75]:
print('Antes:', df.shape)
# Entrevistas realizadas
df = df[df['tipo_entrevista']=='Realizada'].reset_index(drop=True)
print('Depois:', df.shape)

Antes: (293726, 208)
Depois: (279382, 208)

# Criação de novas Features

## Ano Nascimento Inferido pela idade

In [76]:
df['ano_nascimento_inferido'] = np.where(df['ano_nascimento']==9999, 2019 - df['idade'], df['ano_nascimento'])

# IMC

In [77]:
# Calcular o IMC
# Função para calcular o IMC
def calcular_imc(row):
    """
    Calcula o IMC com base no peso (kg) e altura (cm).
    :param row: Linha do DataFrame.
    :return: Valor do IMC (float) ou None se peso ou altura forem nulos.
    """
    if pd.notnull(row['peso']) and pd.notnull(row['altura']) and row['altura'] > 0:
        altura_metros = row['altura'] / 100  # Converter altura de cm para metros
        return row['peso'] / (altura_metros ** 2)
    return None

# Função para classificar o IMC
def classificar_imc(imc):
    if pd.isnull(imc):
        return None, None
    elif imc < 18.5:
        return "Magreza", 0
    elif 18.5 <= imc < 25:
        return "Normal", 0
    elif 25.0 <= imc < 30:
        return "Sobrepeso", 1
    elif 30.0 <= imc < 40:
        return "Obesidade", 2
    elif imc >= 40.0:
        return "Obesidade Grave", 3
    return None, None

# Peso unico, usar medido, ou informado
df['peso'] = np.where(df['peso_final_kg'].isna(), df['peso_info_kg'], df['peso_final_kg'])
# Peso Altura, usar medido, ou informado
df['altura'] = np.where(df['altura_final_cm'].isna(), df['altura_info_cm'], df['altura_final_cm'])

# Aplicar a função ao DataFrame
df['imc'] = df.apply(calcular_imc, axis=1)

# Aplicar a função e criar as colunas 'imc_classificacao' e 'imc_grau_obesidade'
df[['imc_classificacao', 'imc_grau_obesidade']] = df['imc'].apply(
    lambda x: pd.Series(classificar_imc(x))
)

In [78]:
df['imc_classificacao'].value_counts(dropna=False)

imc_classificacao
None               189428
Normal              36618
Sobrepeso           33005
Obesidade           17033
Magreza              2225
Obesidade Grave      1073
Name: count, dtype: int64

## Escolaridade

    D00901 - agrupar
    Escolaridade
        ○ Fundamental
        ○ Medio
        ○ Superior
        ○ Pós Graduação

In [79]:
nivel_educacao_agrupado = {
    1: "Fundamental",  # Creche
    2: "Fundamental",  # Pré-escola
    3: "Fundamental",  # Classe de alfabetização – CA
    4: "Fundamental",  # Alfabetização de jovens e adultos
    5: "Fundamental",  # Antigo primário (elementar)
    6: "Fundamental",  # Antigo ginasial (médio 1º ciclo)
    7: "Fundamental",  # Regular do ensino fundamental ou do 1º grau
    8: "Fundamental",  # Educação de jovens e adultos (EJA) ou supletivo do ensino fundamental
    9: "Médio",        # Antigo científico, clássico etc. (médio 2º ciclo)
    10: "Médio",       # Regular do ensino médio ou do 2º grau
    11: "Médio",       # Educação de jovens e adultos (EJA) ou supletivo do ensino médio
    12: "Superior",    # Superior – graduação
    13: "Pós-graduação",  # Especialização de nível superior (duração mínima de 360 horas)
    14: "Pós-graduação",  # Mestrado
    15: "Pós-graduação",  # Doutorado
    99: "Ignorado"     # Ignorado
}

df['escolaridade'] = df['D00901'].map(nivel_educacao_agrupado)
df['escolaridade'].value_counts(dropna=False)

escolaridade
NaN              101369
Fundamental       77300
Médio             68642
Superior          24223
Pós-graduação      7848
Name: count, dtype: int64

# Peso ao Nascer

In [80]:
# Criar a coluna 'peso_ao_nascer' com base nos valores da coluna 'S11001'
def categorizar_peso_nascimento(peso):
    if pd.isna(peso):  # Tratar valores NaN
        return np.nan
    elif peso < 1500:
        return "Baixo peso extremo"
    elif peso < 2500:
        return "Baixo peso"
    elif 2500 <= peso < 4000:
        return "Adequado"
    elif peso >= 4000:
        return "Macrossomia"
    else:
        return np.nan  # Caso algum valor não se encaixe (opcional)

# Aplicar a função ao DataFrame
df["peso_ao_nascer"] = df["S11001"].apply(categorizar_peso_nascimento)

# Exibir as contagens de cada categoria
print(df["peso_ao_nascer"].value_counts(dropna=False))

peso_ao_nascer
NaN                   276736
Adequado                2206
Baixo peso               223
Macrossomia              185
Baixo peso extremo        32
Name: count, dtype: int64

In [81]:
df['peso_nascer_inferior_2_5'] = np.where(df['S11001'] < 2500, 'Sim', 'Não')
df['peso_nascer_inferior_2_5'].value_counts(dropna=False)

peso_nascer_inferior_2_5
Não    279127
Sim       255
Name: count, dtype: int64

## Prematuro
        S11801 - prematuro
        Classificação Idade Gestacional
             ○ Prematuro extremo	< 28 semanas
             ○ Prematuro moderado a grave: 28 a 31 semanas e 6 dias
             ○ Prematuro tardio: 32 a 36 semanas e 6 dias
             ○ A termo: 37 a 41 semanas e 6 dias
             ○ Pós-termo: ≥ 42 semanas

In [82]:
# Função para categorizar a idade gestacional
def categorizar_idade_gestacional(semanas):
    if pd.isna(semanas):  # Tratar valores NaN
        return np.nan
    elif semanas < 28:
        return "Prematuro extremo"
    elif 28 <= semanas <= 31:
        return "Prematuro moderado a grave"
    elif 32 <= semanas <= 36:
        return "Prematuro tardio"
    elif 37 <= semanas <= 41:
        return "A termo"
    elif semanas >= 42:
        return "Pós-termo"
    else:
        return np.nan  # Caso algum valor não se encaixe (opcional)

# Aplicar a função ao DataFrame
df["Classificação Idade Gestacional"] = df["S11801"].apply(categorizar_idade_gestacional)

# Exibir as contagens de cada categoria
print(df["Classificação Idade Gestacional"].value_counts(dropna=False))

Classificação Idade Gestacional
NaN                           276763
A termo                         2003
Prematuro tardio                 383
Pós-termo                        155
Prematuro extremo                 46
Prematuro moderado a grave        32
Name: count, dtype: int64

In [83]:
df['prematuro'] = np.where(df['S11801']<37, 'Sim', 'Não')
df['prematuro'].value_counts(dropna=False)

prematuro
Não    278921
Sim       461
Name: count, dtype: int64

## Risco de Insulto Perinatal
            Risco de Insulto Perinatal - Boelano
            Considerar como sim as participantes com resposta Não (2) para os seguintes códigos quem tiver resposta 1. Seria classificado sem risco
            ○ S131
            ○ S132
            ○ S133 – Respostas 2 e 3 classificar como Risco sim

In [84]:
df['S131'].value_counts(dropna=False), df['S132'].value_counts(dropna=False), df['S133'].value_counts(dropna=False)

(S131
 NaN    276509
 1.0      2569
 2.0       304
 Name: count, dtype: int64,
 S132
 NaN    276509
 1.0      2689
 2.0       184
 Name: count, dtype: int64,
 S133
 NaN    279198
 3.0       108
 2.0        51
 4.0        16
 1.0         9
 Name: count, dtype: int64)

In [85]:
# df['Risco de Insulto Perinatal'] = np.where((df['S131']==2) | (df['S132']==2) | (df['S133']==2) | (df['S133']==3) , 'Sim', 'Não')
def avaliar_insulto_perinatal(row):
    # Se todos forem NaN, retorna NaN
    if pd.isna(row['S131']) and pd.isna(row['S132']) and pd.isna(row['S133']):
        return np.nan
    # Se qualquer um dos critérios for atendido, retorna 'Sim'
    elif (row['S131'] == 2) or (row['S132'] == 2) or (row['S133'] in [2, 3]):
        return 'Sim'
    else:
        return 'Não'

df['Risco de Insulto Perinatal'] = df.apply(avaliar_insulto_perinatal, axis=1)
df['Risco de Insulto Perinatal'].value_counts(dropna=False)

Risco de Insulto Perinatal
NaN    276509
Não      2536
Sim       337
Name: count, dtype: int64

## Complicações perinatais

    Complicações Perinatais - bolean - Sim para qualquer uma
        ○ Q00202
        ○ Q03002
        ○ R011 ---
        ○ T004
        ○ S082
        ○ S125

In [86]:
# df['Complicações Perinatais'] = np.where(
#     df[['Q00202', 'Q03002', 'T004', 'S082', 'S125']].isin([1]).any(axis=1),
#     'Sim', 'Não'
# )
def avaliar_complicacoes_perinatais(row):
    colunas = ['Q00202', 'Q03002', 'T004', 'S082', 'S125']    
    # Se todas forem NaN, retorna NaN
    if row[colunas].isna().all():
        return np.nan
    # Se qualquer uma for igual a 1, retorna 'Sim'
    elif (row[colunas] == 1).any():
        return 'Sim'
    else:
        return 'Não'

df['Complicações Perinatais'] = df.apply(avaliar_complicacoes_perinatais, axis=1)
df['Complicações Perinatais'].value_counts(dropna=False)

Complicações Perinatais
NaN    188536
Não     88527
Sim      2319
Name: count, dtype: int64

## Comorbidades
Módulo Q - Condições crônicas de saúde
modulo_Q_2019 = [
-    "Q00201",  # Hipertensão
 -   "Q03001",  # Diabetes
  -  "Q060",    # Colesterol alto
   - "Q06306",  # Doença cardíaca
-    "Q055012", # Acidente vascular cerebral (AVC)
 -   "Q092",    # Depressão
-    "Q11006",  # Outra doença mental
-    "Q11604",  # Doença pulmonar crônica
-    "Q120",    # Câncer
-    "Q124",    # Doença renal crônica
-    "Q128",    # Outra doença crônica
]

 Módulo P - Tabagismo
modulo_P_2019 = [
-    "P050",    # Fumante atual
]

In [87]:
df['fumante_atual'] = df['P050'].map({1:1, 2:1})

df['comorbidade'] = np.where(
    df[['Q00201', 'Q03001', 'Q11604', 'Q11006', 'Q092', 'Q120',
        'Q055012', 'Q06306', 'Q060', 'Q124', 'Q128', 'fumante_atual']].isin([1]).any(axis=1),
    'Sim', 'Não'
)

# Criar a coluna 'comorbidade_score' contando quantas colunas possuem o valor 1
df['comorbidade_score'] = df[['Q00201', 'Q03001', 'Q11604', 'Q11006', 'Q092', 'Q120',
                              'Q055012', 'Q06306', 'Q060', 'Q124', 'Q128',  'fumante_atual']].eq(1).sum(axis=1)

df['comorbidade'].value_counts(dropna=False), df['comorbidade_score'].value_counts(dropna=False)

(comorbidade
 Não    230335
 Sim     49047
 Name: count, dtype: int64,
 comorbidade_score
 0    230335
 1     26318
 2     13024
 3      6064
 4      2461
 5       849
 6       260
 7        57
 8        12
 9         2
 Name: count, dtype: int64)

In [ ]:
# Módulo Q - Condições crônicas de saúde
modulo_Q_2019 = {
    "hipertensao": "Q00201",
    "diabetes": "Q03001",
    "colesterol_alto": "Q060",
    "doenca_cardiaca": "Q06306",
    "avc": "Q055012",
    "depressao": "Q092",
    "outra_doenca_mental": "Q11006",
    "doenca_pulmonar_cronica": "Q11604",
    "cancer": "Q120",
    "doenca_renal_cronica": "Q124",
    "outra_doenca_cronica": "Q128"
}

# Módulo P - Tabagismo
modulo_P_2019 = {
    "fumante_atual": "fumante_atual"
}

# Criar colunas binárias individuais (0 = não, 1 = sim)
for nome, col in {**modulo_Q_2019, **modulo_P_2019}.items():
    df[nome] = np.where(df[col] == 1, 'Sim', 'Não')

## Renda per Capta

In [89]:
salario_minimo = 998.0

# Definição dos pontos de corte (bins), em reais
bins = [
    0,
    1*salario_minimo,
    2*salario_minimo,
    3*salario_minimo,
    5*salario_minimo,
    np.inf  # Limite superior aberto
]

# Rótulos correspondentes às faixas
labels = [
    "<1 SM",
    "1 a <2 SM",
    "2 a <3 SM",
    "3 a <5 SM",
    "≥5 SM"
]

# df["faixa_renda_per_capta"] = pd.cut(df["E01602"], bins=bins, labels=labels, right=False)
df["faixa_renda_per_capta"] = pd.cut(df["VDF003"].fillna(0), bins=bins, labels=labels, right=False)
df["faixa_renda_per_capta"].value_counts(dropna=False)

faixa_renda_per_capta
<1 SM        165121
1 a <2 SM     69923
2 a <3 SM     19849
3 a <5 SM     13392
≥5 SM         11097
Name: count, dtype: int64

# Atividade Física

In [90]:
df['atividade_fisica'] = np.where(df['P034']==1, 'Sim', 'Não')

# Pré Natal Adequado

modulo_S_2019 = [
-    "S065",    # Histórico de gravidez (já esteve grávida alguma vez)
-    "S068",    # Recebeu cuidado pré-natal na última gestação
-    "S06901",  # Início do pré-natal até a 13ª semana (início adequado)
-    "S070",    # Número mínimo de 6 consultas de pré-natal
-    "S076",    # Realização de exames de sangue durante o pré-natal
-    "S077",    # Realização de exames de urina durante o pré-natal
-    "S080",    # Teste de sífilis realizado durante o pré-natal
-    "S090",    # Teste de HIV realizado durante o pré-natal
]

In [91]:
# Criar coluna binária: 1 = cuidado adequado, 0 = não adequado
df['pre_natal_adequado'] = np.where(
    (df['S065'] == 1) &         # histórico de gravidez
    (df['S068'] == 1) &         # recebeu pré-natal
    (df['S06901'] <= 13) &       # início até 13ª semana
    (df['S070'] >= 6) &         # seis ou mais consultas
    (df['S076'] == 1) &         # exame de sangue
    (df['S077'] == 1) &         # exame de urina
    (df['S080'] == 1) &         # teste de sífilis
    (df['S090'] == 1),           # teste de HIV
    'Sim', 'Não'
)

df['pre_natal_adequado'].value_counts(dropna=False)

pre_natal_adequado
Não    278499
Sim       883
Name: count, dtype: int64

# Cesariana

In [92]:
df['cesaria'] = np.where(df['S115']==2, 'Sim', 'Não')
df['cesaria'].value_counts(dropna=False)

cesaria
Não    277866
Sim      1516
Name: count, dtype: int64

# Clusterização

# Mães - Mulheres que tiveram filhos

- Usar as variáveis do Módulo S para identificar mulheres que tiveram Filhos (S066)
- Que informaram data de ultimo parto S06703
- Ver se o ultimo parto foi nos ultimos 6~7 anos. Para cruzar com o cluster de crianças e bater que elas de fato são mae e filha (aproximadamente)

In [93]:
pd.set_option('display.max_rows', 100)

In [94]:
# Guardar volumetrias para consulta futura
fil1 = (df.idade >= 15)
print(f'Quantidade de pessoas com 15 anos ou mais: {fil1.sum()}')

fil2 = (df.sexo=='Feminino')
print(f'Quantidade de mulheres: {fil2.sum()}')

fil3 = (df.S066>0) & (df.S066<99)
print(f'Quantidade de mulheres que tiveram 1 ou mais de 1 parto: {fil3.sum()}')

fil4 = (df.S06703>0) & (df.S06703 <9999)
print(f'Quantidade de mulheres que informaram a data do ultimo parto: {fil4.sum()}')

# fil5 = (df.S06703 >= 2011)
# print(f'Quantidade de mulheres que tiveram parto depois de 2011: {fil5.sum()}')

print(f'Quantidade de mulheres com 15 anos ou mais: {(fil1 & fil2).sum()}')
print(f'Quantidade de mulheres com 15 anos ou mais que tiveram mais de 1 parto: {(fil1 & fil2 & fil3).sum()}')
print(f'Quantidade de mulheres com 15 anos ou mais que tiveram mais de 1 parto e informaram data: {(fil1 & fil2 & fil3 & fil4).sum()}')
print(f'Quantidade de mulheres com 15 anos ou mais que tiveram mais de 1 parto e informaram data e o parto foi depois de 2011: {(fil1 & fil2 & fil3 & fil4).sum()}')

Quantidade de pessoas com 15 anos ou mais: 221095
Quantidade de mulheres: 144940
Quantidade de mulheres que tiveram 1 ou mais de 1 parto: 36481
Quantidade de mulheres que informaram a data do ultimo parto: 35869
Quantidade de mulheres com 15 anos ou mais: 116225
Quantidade de mulheres com 15 anos ou mais que tiveram mais de 1 parto: 36481
Quantidade de mulheres com 15 anos ou mais que tiveram mais de 1 parto e informaram data: 35869
Quantidade de mulheres com 15 anos ou mais que tiveram mais de 1 parto e informaram data e o parto foi depois de 2011: 35869

In [95]:
df_maes = df[(fil1 & fil2 & fil3 & fil4)].copy().reset_index(drop=True)
df_maes.shape

(35869, 239)

### Flag de Parto em Idade avançada

In [96]:
df_maes['idade_ultimo_parto'] = df_maes['S06703'] - df_maes['ano_nascimento_inferido']
df_maes['idade_ultimo_parto'].describe(percentiles=[0.01,0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.92, 0.94, 0.96, 0.98, 0.99])

count    35869.000000
mean        29.141571
std          6.883644
min          8.000000
1%          16.000000
10%         21.000000
20%         23.000000
30%         25.000000
40%         27.000000
50%         29.000000
60%         30.000000
70%         33.000000
80%         35.000000
90%         38.000000
92%         39.000000
94%         40.000000
96%         42.000000
98%         44.000000
99%         46.000000
max         87.000000
Name: idade_ultimo_parto, dtype: float64

In [97]:
df_maes['parto_idade_avancada'] = np.where(df_maes['idade_ultimo_parto']>=35, 1, 0)

### Retirar maes muito novas ou muito velhas
- Outliers

In [98]:
df_maes = df_maes[df_maes['idade_ultimo_parto'] >= 15]
df_maes = df_maes[df_maes['idade_ultimo_parto'] <= 55]

In [99]:
df_maes['parto_idade_avancada'].value_counts(dropna=False)

parto_idade_avancada
0    27882
1     7814
Name: count, dtype: int64

In [100]:
df_maes['parto_idade_avancada'].value_counts(dropna=False, normalize=True)

parto_idade_avancada
0    0.781096
1    0.218904
Name: proportion, dtype: float64

In [101]:
df_maes.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 35696 entries, 0 to 35868
Data columns (total 241 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    V0001                            35696 non-null  int64
 1    V0024                            35696 non-null  int64
 2    UPA_PNS                          35696 non-null  int64
 3    V0006_PNS                        35696 non-null  int64
 4    V0015                            35696 non-null  int64
 5    V0022                            35696 non-null  float64
 6    V0026                            35696 non-null  int64
 7    V0031                            35696 non-null  int64
 8    V0025A                           35696 non-null  float64
 9    V0025B                           2606 non-null   float64
 10   C001                             35696 non-null  float64
 11   C00301                           35696 non-null  float64
 12   C006                             35696 non-null  float64
 13   C00701                           35696 non-null  float64
 14   C00702                           35696 non-null  float64
 15   C00703                           35696 non-null  float64
 16   C008                             35696 non-null  float64
 17   C009                             35696 non-null  float64
 18   C011                             35696 non-null  float64
 19   D00201                           35696 non-null  float64
 20   D00901                           31704 non-null  float64
 21   E01602                           16353 non-null  float64
 22   E017                             16845 non-null  float64
 23   G033                             35696 non-null  float64
 24   G046                             20215 non-null  float64
 25   G047                             15481 non-null  float64
 26   G049                             396 non-null    float64
 27   G051                             396 non-null    float64
 28   G053                             396 non-null    float64
 29   G059                             35696 non-null  float64
 30   G060                             828 non-null    float64
 31   G062                             828 non-null    float64
 32   G064                             828 non-null    float64
 33   G066                             828 non-null    float64
 34   G070                             828 non-null    float64
 35   G072                             35696 non-null  float64
 36   G073                             245 non-null    float64
 37   G079                             245 non-null    float64
 38   G083                             35696 non-null  float64
 39   G084                             14480 non-null  float64
 40   J001                             35696 non-null  float64
 41   J00402                           4446 non-null   float64
 42   J007                             35696 non-null  float64
 43   J012                             30993 non-null  float64
 44   L01701                           0 non-null      float64
 45   L018                             0 non-null      float64
 46   L019                             0 non-null      float64
 47   L021                             0 non-null      float64
 48   L033                             0 non-null      float64
 49   L037                             0 non-null      float64
 50   L038                             0 non-null      float64
 51   L039                             0 non-null      float64
 52   L040                             0 non-null      float64
 53   P00103                           32517 non-null  float64
 54   P00104                           35127 non-null  float64
 55   P00403                           28311 non-null  float64
 56   P00404                           35127 non-null  float64
 57   P027                             35696 non-null  float64
 58   P034                             35696 non-null  float64
 59   P035                             12376 non-null  float64
 60   P050                             35696 non-null  float64
 61   P052                             32104 non-null  float64
 62   Q00201                           35481 non-null  float64
 63   Q00202                           12182 non-null  float64
 64   Q003                             11006 non-null  float64
 65   Q028                             11006 non-null  float64
 66   Q03001                           34515 non-null  float64
 67   Q03002                           3754 non-null   float64
 68   Q031                             3505 non-null   float64
 69   Q055011                          3160 non-null   float64
 70   Q055012                          3160 non-null   float64
 71   Q055013                          3160 non-null   float64
 72   Q060                             34275 non-null  float64
 73   Q061                             7151 non-null   float64
 74   Q06306                           35696 non-null  float64
 75   Q06307                           2259 non-null   float64
 76   Q06308                           2259 non-null   float64
 77   Q06309                           2259 non-null   float64
 78   Q06310                           2259 non-null   float64
 79   Q064                             2259 non-null   float64
 80   Q068                             35696 non-null  float64
 81   Q070                             892 non-null    float64
 82   Q074                             35696 non-null  float64
 83   Q075                             2014 non-null   float64
 84   Q079                             35696 non-null  float64
 85   Q080                             4608 non-null   float64
 86   Q084                             35696 non-null  float64
 87   Q085                             9037 non-null   float64
 88   Q087                             9037 non-null   float64
 89   Q088                             35696 non-null  float64
 90   Q08901                           886 non-null    float64
 91   Q091                             886 non-null    float64
 92   Q092                             35696 non-null  float64
 93   Q09301                           5079 non-null   float64
 94   Q109                             5079 non-null   float64
 95   Q11006                           35696 non-null  float64
 96   Q11007                           2525 non-null   float64
 97   Q11008                           2525 non-null   float64
 98   Q11009                           2525 non-null   float64
 99   Q111                             2525 non-null   float64
 100  Q11604                           35696 non-null  float64
 101  Q11605                           564 non-null    float64
 102  Q11606                           564 non-null    float64
 103  Q11701                           564 non-null    float64
 104  Q120                             35696 non-null  float64
 105  Q12201                           1036 non-null   float64
 106  Q124                             35696 non-null  float64
 107  Q125                             577 non-null    float64
 108  Q128                             35696 non-null  float64
 109  R011                             3690 non-null   float64
 110  R025                             35696 non-null  float64
 111  R026                             32006 non-null  float64
 112  R027                             14028 non-null  float64
 113  R028                             14028 non-null  float64
 114  R029                             13515 non-null  float64
 115  R034                             15708 non-null  float64
 116  R035                             6904 non-null   float64
 117  R03601                           8804 non-null   float64
 118  R037                             15708 non-null  float64
 119  R038                             18 non-null     float64
 120  S065                             35696 non-null  float64
 121  S066                             35696 non-null  float64
 122  S06703                           35696 non-null  float64
 123  S068                             2896 non-null   float64
 124  S06901                           2817 non-null   float64
 125  S06902                           2817 non-null   float64
 126  S070                             2817 non-null   float64
 127  S076                             2817 non-null   float64
 128  S077                             2817 non-null   float64
 129  S080                             2817 non-null   float64
 130  S082                             2155 non-null   float64
 131  S083                             8 non-null      float64
 132  S086                             509 non-null    float64
 133  S087                             15 non-null     float64
 134  S090                             2817 non-null   float64
 135  S095                             2817 non-null   float64
 136  S096                             2817 non-null   float64
 137  S098                             2817 non-null   float64
 138  S099                             1886 non-null   float64
 139  S09901                           1266 non-null   float64
 140  S110                             2844 non-null   float64
 141  S11001                           2641 non-null   float64
 142  S112                             2896 non-null   float64
 143  S115                             2896 non-null   float64
 144  S116                             1511 non-null   float64
 145  S117                             1511 non-null   float64
 146  S118                             2896 non-null   float64
 147  S11801                           2612 non-null   float64
 148  S125                             2896 non-null   float64
 149  S126                             2896 non-null   float64
 150  S127                             299 non-null    float64
 151  S130                             2896 non-null   float64
 152  S131                             2862 non-null   float64
 153  S132                             2862 non-null   float64
 154  S133                             182 non-null    float64
 155  S134                             2896 non-null   float64
 156  S136                             2896 non-null   float64
 157  T004                             35696 non-null  float64
 158  W001                             2606 non-null   float64
 159  W00101                           2508 non-null   float64
 160  W00102                           2508 non-null   float64
 161  W00103                           2561 non-null   float64
 162  W00201                           2507 non-null   float64
 163  W00202                           2507 non-null   float64
 164  W00203                           2561 non-null   float64
 165  V0029                            35696 non-null  float64
 166  V00291                           35696 non-null  float64
 167  V00282                           35696 non-null  float64
 168  V00283                           35696 non-null  float64
 169  V00293                           35696 non-null  float64
 170  V00303                           2561 non-null   float64
 171  VDE014                           16845 non-null  float64
 172  VDF003                           35687 non-null  float64
 173  VDF004                           35687 non-null  float64
 174  VDL001                           0 non-null      float64
 175  chave_domicio                    35696 non-null  object
 176  chave_pessoa                     35696 non-null  object
 177  peso_morador_selec               35696 non-null  float64
 178  UF                               35696 non-null  int64
 179  Estrato                          35696 non-null  int64
 180  UPA                              35696 non-null  int64
 181  N_ordem_domicilio_PNS            35696 non-null  int64
 182  N_ordem_morador                  35696 non-null  float64
 183  N_pessoas_domicilio              35696 non-null  float64
 184  Quantidade_moradores             35696 non-null  float64
 185  tipo_entrevista                  35696 non-null  object
 186  regiao_metropolitana             35696 non-null  object
 187  capital_metropolitana            35696 non-null  object
 188  sexo                             35696 non-null  object
 189  dia_nascimento                   35696 non-null  float64
 190  mes_nascimento                   35696 non-null  float64
 191  ano_nascimento                   35696 non-null  float64
 192  idade                            35696 non-null  float64
 193  estado_civil                     35696 non-null  object
 194  peso_info_kg                     32517 non-null  float64
 195  peso_final_kg                    35127 non-null  float64
 196  altura_info_cm                   28311 non-null  float64
 197  altura_final_cm                  35127 non-null  float64
 198  antropometria_aferida_morador    2606 non-null   float64
 199  peso_1_pesagem_kg                2508 non-null   float64
 200  peso_2_pesagem_kg                2508 non-null   float64
 201  peso_final_medido_kg             2561 non-null   float64
 202  altura_1_medicao_cm              2507 non-null   float64
 203  altura_2_medicao_cm              2507 non-null   float64
 204  altura_final_medida_cm           2561 non-null   float64
 205  UF_sigla                         35696 non-null  object
 206  regiao_brasileira                35696 non-null  object
 207  raca                             35696 non-null  object
 208  ano_nascimento_inferido          35696 non-null  float64
 209  peso                             35127 non-null  float64
 210  altura                           35127 non-null  float64
 211  imc                              35127 non-null  float64
 212  imc_classificacao                35127 non-null  object
 213  imc_grau_obesidade               35127 non-null  float64
 214  escolaridade                     31704 non-null  object
 215  peso_ao_nascer                   2641 non-null   object
 216  peso_nascer_inferior_2_5         35696 non-null  object
 217  Classificação Idade Gestacional  2612 non-null   object
 218  prematuro                        35696 non-null  object
 219  Risco de Insulto Perinatal       2862 non-null   object
 220  Complicações Perinatais          35696 non-null  object
 221  fumante_atual                    35696 non-null  int64
 222  comorbidade                      35696 non-null  object
 223  comorbidade_score                35696 non-null  int64
 224  hipertensao                      35696 non-null  int64
 225  diabetes                         35696 non-null  int64
 226  colesterol_alto                  35696 non-null  int64
 227  doenca_cardiaca                  35696 non-null  int64
 228  avc                              35696 non-null  int64
 229  depressao                        35696 non-null  int64
 230  outra_doenca_mental              35696 non-null  int64
 231  doenca_pulmonar_cronica          35696 non-null  int64
 232  cancer                           35696 non-null  int64
 233  doenca_renal_cronica             35696 non-null  int64
 234  outra_doenca_cronica             35696 non-null  int64
 235  faixa_renda_per_capta            35696 non-null  category
 236  atividade_fisica                 35696 non-null  object
 237  pre_natal_adequado               35696 non-null  object
 238  cesaria                          35696 non-null  object
 239  idade_ultimo_parto               35696 non-null  float64
 240  parto_idade_avancada             35696 non-null  int64
dtypes: category(1), float64(193), int64(25), object(22)
memory usage: 65.7+ MB

In [102]:
# df_maes.to_csv('data/df_maes_2019.csv', index=False)

# Pipe Filhos

# Deficiencias

In [103]:
modulo =[
    'G033',
    # 'G047',
 'G049',
 'G051',
 'G053',
 'G059',
 'G060',
 'G062',
 'G064',
 'G066',
#  'G070',
 'G072',
 'G073',
#  'G079',
#  'G083',
 'G084',
 'modulo_pre'
 ]

a = {
    "G047":{
        1: "Não, nenhuma dificuldade",
        2: "Sim, alguma dificuldade",
        3: "Sim, muita dificuldade",
        4: "Sim, não consegue de modo algum",
        9: "Ignorado"
    },
    "G070":{
        1: "Não, nenhuma dificuldade",
        2: "Sim, alguma dificuldade",
        3: "Sim, muita dificuldade",
        4: "Sim, não consegue de modo algum",
        9: "Ignorado"
    },
    "G079":{
        1: "Não, nenhuma dificuldade",
        2: "Sim, alguma dificuldade",
        3: "Sim, muita dificuldade",
        4: "Sim, não consegue de modo algum",
        9: "Ignorado"
    },
    "G083":{
        1: "Não, nenhuma dificuldade",
        2: "Sim, alguma dificuldade",
        3: "Sim, muita dificuldade",
        4: "Sim, não consegue de modo algum",
        9: "Ignorado"
    },

}

modulo_pre =[
    'G047',
    'G070',
    'G079',
    'G083',
 ]

df['modulo_pre'] = np.where(
    df[modulo_pre].isin([2,3,4]).any(axis=1),
    1,  # tem
    0   # não tem
)
df['deficiencia'] = np.where(
    df[modulo].isin([1]).any(axis=1),
    1,  # tem
    0   # não tem
)
df['deficiencia'].value_counts(dropna=False)

deficiencia
0    147135
1    132247
Name: count, dtype: int64

# Vacinas

In [104]:

# Checa se calendário vacinal é adequado até os 6 anos e cria uma coluna
# Somente os anos completos foram considerados na idade, sem os meses e dias
# A conta foi inclusiva:
# as vacinas de 2 meses, se não aplicadas em uma criança de 11 meses, ainda são consideradas do 1º ano
# e, portanto, o esquema vacinal está adequado

# idade: numero mínimo de status vacinal para esta idade, conforme dicionário
# Considerei registro ilegível como válido

N_minimo_doses = {
    # penta
    # D1 aos 2 meses, D2 aos 4, D3 aos 6 meses; reforço com 15m e depois com 4a.
    'L037': {
        0: 1, # minimo 1 dose
        1: 4, # minimo 3 doses
        2: 5, # minimo 1o reforço
        3: 5,
        4: 5,
        5: 6, #minimo 2o reforço
        6: 6,
    },

    # Vacina da polio (VIP/VOP)
    # D1 aos 2 meses, d2 4m, d3 6m, r1 15m, r2 4a
    'L038' : {
        0: 1, # minimo 1 dose
        1: 4, # minimo 3 doses
        2: 5, # minimo 1o reforço
        3: 5,
        4: 5,
        5: 6, #minimo 2o reforço
        6: 6,
    },

    # pneumo
    # d1 2m, d2 4m, reforço 12m
    'L039' : {
        0: 1,
        1: 4, # 1o reforço aos 12m
        2: 4,
        3: 4,
        4: 4,
        5: 4,
        6: 4,
    },

    # Triplice viral
    # D1 aos 12 meses, reforço na adolescência
    'L040' : {
        0: 1,
        1: 2, # D1 aos 12 meses
        2: 2,
        3: 2,
        4: 2,
        5: 2,
        6: 2,
    }
}

def checar_estado_vacinal(idade, coluna_vacinas, N_minimo):
  if idade not in N_minimo:
    return np.nan

  # pega o estado vacinal da coluna
  estado_vacinal = coluna_vacinas

  # Compara se o número de doses é maior que o limiar para a idade
  return estado_vacinal >= N_minimo[idade]

# Aplica a lógica para cada coluna de vacina e cria nova coluna com estado válido ou não
for coluna_vacina in ['L037', 'L038', 'L039', 'L040']:
    df[f'{coluna_vacina}_status'] = df.apply(
        lambda row: checar_estado_vacinal(row['idade'], row[coluna_vacina], N_minimo_doses[coluna_vacina]), axis=1
    )

# Cria uma coluna final para verificar se todas as vacinas estão adequadas
df['estado_vacinal'] = df[['L037_status', 'L038_status', 'L039_status', 'L040_status']].fillna(False).all(axis=1)

# Exibe o resumo do estado vacinal
print(df['estado_vacinal'].value_counts(dropna=False, sort=False))

estado_vacinal
False    276030
True       3352
Name: count, dtype: int64

C:\Users\leand\AppData\Local\Temp\ipykernel_15836\3494671368.py:77: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['estado_vacinal'] = df[['L037_status', 'L038_status', 'L039_status', 'L040_status']].fillna(False).all(axis=1)

In [105]:
# Seguir com a variavel de Idade para segmentar - Referencia temporal das respostas na data da entrevista
df[(df.ano_nascimento>= 2012)&(df.ano_nascimento< 9999)]['idade'].value_counts(dropna=False)

idade
6.0    3616
4.0    3582
5.0    3508
3.0    3464
1.0    3411
0.0    3349
2.0    3270
7.0    2150
Name: count, dtype: int64

In [106]:
df_children = df[(df.idade <= 7)].copy()
df_children = df_children.sort_values(by=['idade'], ascending=[True])
df_children.shape, df_children.drop_duplicates(subset=['chave_domicio']).shape

((29211, 246), (22591, 246))

In [107]:

# df_children.to_csv('data/df_criancas_2019.csv', index=False)

In [108]:
df_children.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 29211 entries, 157188 to 221
Data columns (total 246 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    V0001                            29211 non-null  int64
 1    V0024                            29211 non-null  int64
 2    UPA_PNS                          29211 non-null  int64
 3    V0006_PNS                        29211 non-null  int64
 4    V0015                            29211 non-null  int64
 5    V0022                            29211 non-null  float64
 6    V0026                            29211 non-null  int64
 7    V0031                            29211 non-null  int64
 8    V0025A                           29211 non-null  float64
 9    V0025B                           2168 non-null   float64
 10   C001                             29211 non-null  float64
 11   C00301                           29211 non-null  float64
 12   C006                             29211 non-null  float64
 13   C00701                           29211 non-null  float64
 14   C00702                           29211 non-null  float64
 15   C00703                           29211 non-null  float64
 16   C008                             29211 non-null  float64
 17   C009                             29211 non-null  float64
 18   C011                             0 non-null      float64
 19   D00201                           29211 non-null  float64
 20   D00901                           395 non-null    float64
 21   E01602                           0 non-null      float64
 22   E017                             0 non-null      float64
 23   G033                             22328 non-null  float64
 24   G046                             750 non-null    float64
 25   G047                             21578 non-null  float64
 26   G049                             27 non-null     float64
 27   G051                             27 non-null     float64
 28   G053                             27 non-null     float64
 29   G059                             22328 non-null  float64
 30   G060                             38 non-null     float64
 31   G062                             38 non-null     float64
 32   G064                             38 non-null     float64
 33   G066                             38 non-null     float64
 34   G070                             38 non-null     float64
 35   G072                             22328 non-null  float64
 36   G073                             66 non-null     float64
 37   G079                             29 non-null     float64
 38   G083                             22328 non-null  float64
 39   G084                             1351 non-null   float64
 40   J001                             29211 non-null  float64
 41   J00402                           2220 non-null   float64
 42   J007                             29211 non-null  float64
 43   J012                             24774 non-null  float64
 44   L01701                           6632 non-null   float64
 45   L018                             293 non-null    float64
 46   L019                             6632 non-null   float64
 47   L021                             6632 non-null   float64
 48   L033                             3683 non-null   float64
 49   L037                             4856 non-null   float64
 50   L038                             4856 non-null   float64
 51   L039                             4856 non-null   float64
 52   L040                             4856 non-null   float64
 53   P00103                           0 non-null      float64
 54   P00104                           0 non-null      float64
 55   P00403                           0 non-null      float64
 56   P00404                           0 non-null      float64
 57   P027                             0 non-null      float64
 58   P034                             0 non-null      float64
 59   P035                             0 non-null      float64
 60   P050                             0 non-null      float64
 61   P052                             0 non-null      float64
 62   Q00201                           0 non-null      float64
 63   Q00202                           0 non-null      float64
 64   Q003                             0 non-null      float64
 65   Q028                             0 non-null      float64
 66   Q03001                           0 non-null      float64
 67   Q03002                           0 non-null      float64
 68   Q031                             0 non-null      float64
 69   Q055011                          0 non-null      float64
 70   Q055012                          0 non-null      float64
 71   Q055013                          0 non-null      float64
 72   Q060                             0 non-null      float64
 73   Q061                             0 non-null      float64
 74   Q06306                           0 non-null      float64
 75   Q06307                           0 non-null      float64
 76   Q06308                           0 non-null      float64
 77   Q06309                           0 non-null      float64
 78   Q06310                           0 non-null      float64
 79   Q064                             0 non-null      float64
 80   Q068                             0 non-null      float64
 81   Q070                             0 non-null      float64
 82   Q074                             0 non-null      float64
 83   Q075                             0 non-null      float64
 84   Q079                             0 non-null      float64
 85   Q080                             0 non-null      float64
 86   Q084                             0 non-null      float64
 87   Q085                             0 non-null      float64
 88   Q087                             0 non-null      float64
 89   Q088                             0 non-null      float64
 90   Q08901                           0 non-null      float64
 91   Q091                             0 non-null      float64
 92   Q092                             0 non-null      float64
 93   Q09301                           0 non-null      float64
 94   Q109                             0 non-null      float64
 95   Q11006                           0 non-null      float64
 96   Q11007                           0 non-null      float64
 97   Q11008                           0 non-null      float64
 98   Q11009                           0 non-null      float64
 99   Q111                             0 non-null      float64
 100  Q11604                           0 non-null      float64
 101  Q11605                           0 non-null      float64
 102  Q11606                           0 non-null      float64
 103  Q11701                           0 non-null      float64
 104  Q120                             0 non-null      float64
 105  Q12201                           0 non-null      float64
 106  Q124                             0 non-null      float64
 107  Q125                             0 non-null      float64
 108  Q128                             0 non-null      float64
 109  R011                             0 non-null      float64
 110  R025                             0 non-null      float64
 111  R026                             0 non-null      float64
 112  R027                             0 non-null      float64
 113  R028                             0 non-null      float64
 114  R029                             0 non-null      float64
 115  R034                             0 non-null      float64
 116  R035                             0 non-null      float64
 117  R03601                           0 non-null      float64
 118  R037                             0 non-null      float64
 119  R038                             0 non-null      float64
 120  S065                             0 non-null      float64
 121  S066                             0 non-null      float64
 122  S06703                           0 non-null      float64
 123  S068                             0 non-null      float64
 124  S06901                           0 non-null      float64
 125  S06902                           0 non-null      float64
 126  S070                             0 non-null      float64
 127  S076                             0 non-null      float64
 128  S077                             0 non-null      float64
 129  S080                             0 non-null      float64
 130  S082                             0 non-null      float64
 131  S083                             0 non-null      float64
 132  S086                             0 non-null      float64
 133  S087                             0 non-null      float64
 134  S090                             0 non-null      float64
 135  S095                             0 non-null      float64
 136  S096                             0 non-null      float64
 137  S098                             0 non-null      float64
 138  S099                             0 non-null      float64
 139  S09901                           0 non-null      float64
 140  S110                             0 non-null      float64
 141  S11001                           0 non-null      float64
 142  S112                             0 non-null      float64
 143  S115                             0 non-null      float64
 144  S116                             0 non-null      float64
 145  S117                             0 non-null      float64
 146  S118                             0 non-null      float64
 147  S11801                           0 non-null      float64
 148  S125                             0 non-null      float64
 149  S126                             0 non-null      float64
 150  S127                             0 non-null      float64
 151  S130                             0 non-null      float64
 152  S131                             0 non-null      float64
 153  S132                             0 non-null      float64
 154  S133                             0 non-null      float64
 155  S134                             0 non-null      float64
 156  S136                             0 non-null      float64
 157  T004                             0 non-null      float64
 158  W001                             0 non-null      float64
 159  W00101                           0 non-null      float64
 160  W00102                           0 non-null      float64
 161  W00103                           0 non-null      float64
 162  W00201                           0 non-null      float64
 163  W00202                           0 non-null      float64
 164  W00203                           0 non-null      float64
 165  V0029                            0 non-null      float64
 166  V00291                           0 non-null      float64
 167  V00282                           29211 non-null  float64
 168  V00283                           29211 non-null  float64
 169  V00293                           0 non-null      float64
 170  V00303                           0 non-null      float64
 171  VDE014                           0 non-null      float64
 172  VDF003                           29208 non-null  float64
 173  VDF004                           29208 non-null  float64
 174  VDL001                           6632 non-null   float64
 175  chave_domicio                    29211 non-null  object
 176  chave_pessoa                     29211 non-null  object
 177  peso_morador_selec               0 non-null      float64
 178  UF                               29211 non-null  int64
 179  Estrato                          29211 non-null  int64
 180  UPA                              29211 non-null  int64
 181  N_ordem_domicilio_PNS            29211 non-null  int64
 182  N_ordem_morador                  29211 non-null  float64
 183  N_pessoas_domicilio              29211 non-null  float64
 184  Quantidade_moradores             29211 non-null  float64
 185  tipo_entrevista                  29211 non-null  object
 186  regiao_metropolitana             29211 non-null  object
 187  capital_metropolitana            29211 non-null  object
 188  sexo                             29211 non-null  object
 189  dia_nascimento                   29211 non-null  float64
 190  mes_nascimento                   29211 non-null  float64
 191  ano_nascimento                   29211 non-null  float64
 192  idade                            29211 non-null  float64
 193  estado_civil                     29211 non-null  object
 194  peso_info_kg                     0 non-null      float64
 195  peso_final_kg                    0 non-null      float64
 196  altura_info_cm                   0 non-null      float64
 197  altura_final_cm                  0 non-null      float64
 198  antropometria_aferida_morador    0 non-null      float64
 199  peso_1_pesagem_kg                0 non-null      float64
 200  peso_2_pesagem_kg                0 non-null      float64
 201  peso_final_medido_kg             0 non-null      float64
 202  altura_1_medicao_cm              0 non-null      float64
 203  altura_2_medicao_cm              0 non-null      float64
 204  altura_final_medida_cm           0 non-null      float64
 205  UF_sigla                         29211 non-null  object
 206  regiao_brasileira                29211 non-null  object
 207  raca                             29211 non-null  object
 208  ano_nascimento_inferido          29211 non-null  float64
 209  peso                             0 non-null      float64
 210  altura                           0 non-null      float64
 211  imc                              0 non-null      float64
 212  imc_classificacao                0 non-null      object
 213  imc_grau_obesidade               0 non-null      float64
 214  escolaridade                     395 non-null    object
 215  peso_ao_nascer                   0 non-null      object
 216  peso_nascer_inferior_2_5         29211 non-null  object
 217  Classificação Idade Gestacional  0 non-null      object
 218  prematuro                        29211 non-null  object
 219  Risco de Insulto Perinatal       0 non-null      object
 220  Complicações Perinatais          0 non-null      object
 221  fumante_atual                    29211 non-null  int64
 222  comorbidade                      29211 non-null  object
 223  comorbidade_score                29211 non-null  int64
 224  hipertensao                      29211 non-null  int64
 225  diabetes                         29211 non-null  int64
 226  colesterol_alto                  29211 non-null  int64
 227  doenca_cardiaca                  29211 non-null  int64
 228  avc                              29211 non-null  int64
 229  depressao                        29211 non-null  int64
 230  outra_doenca_mental              29211 non-null  int64
 231  doenca_pulmonar_cronica          29211 non-null  int64
 232  cancer                           29211 non-null  int64
 233  doenca_renal_cronica             29211 non-null  int64
 234  outra_doenca_cronica             29211 non-null  int64
 235  faixa_renda_per_capta            29211 non-null  category
 236  atividade_fisica                 29211 non-null  object
 237  pre_natal_adequado               29211 non-null  object
 238  cesaria                          29211 non-null  object
 239  modulo_pre                       29211 non-null  int64
 240  deficiencia                      29211 non-null  int64
 241  L037_status                      25353 non-null  object
 242  L038_status                      25353 non-null  object
 243  L039_status                      25353 non-null  object
 244  L040_status                      25353 non-null  object
 245  estado_vacinal                   29211 non-null  bool
dtypes: bool(1), category(1), float64(192), int64(26), object(26)
memory usage: 54.7+ MB

# Cruzar os Dataframes para criar o de interesse

In [109]:
# Retirar crianças mais velhas, questionario sobre a mais nova
df_children = df_children.drop_duplicates(subset=['chave_domicio'])

In [110]:
df_aux = pd.merge(df_children, df_maes, on="chave_domicio", how="inner")
df_children.shape, df_maes.shape, df_aux.shape

((22591, 246), (35696, 241), (10575, 486))

In [111]:
df_aux = df_aux[['chave_domicio']].drop_duplicates().reset_index(drop=True)
df_aux['filho'] = 1
df_aux.shape

(10575, 2)

In [112]:
df_grupo_maes = pd.merge(df_maes, df_aux, on="chave_domicio", how="inner" )
df_grupo_maes['filho'] = df_grupo_maes['filho'].fillna(0)
df_grupo_maes.shape

(10575, 242)

In [113]:
df_grupo_maes.parto_idade_avancada.value_counts()

parto_idade_avancada
0    8445
1    2130
Name: count, dtype: int64

In [114]:
# Criar um grupo de filhos com maes em idade avançada
df_grupo_criancas = pd.merge(df_children, df_grupo_maes[['chave_domicio', 'idade_ultimo_parto', 'parto_idade_avancada']], on="chave_domicio", how="inner" )
df_grupo_criancas.shape

(10575, 248)

# Manter apenas as mesmas colunas de 2013 e 2019

In [115]:
colunas = ['V0024', 'UPA_PNS', 'V00291','UF',
       'regiao_metropolitana', 'capital_metropolitana', 'sexo',
       'dia_nascimento', 'mes_nascimento', 'ano_nascimento', 'idade',
       'estado_civil', 'UF_sigla', 'regiao_brasileira', 'raca', 
       'ano_nascimento_inferido','escolaridade','idade_ultimo_parto', 
       'parto_idade_avancada', 'filho',
       'faixa_renda_per_capta', 'imc_classificacao', 'comorbidade', 'atividade_fisica', 'pre_natal_adequado',
       "hipertensao",
       "fumante_atual",
       "diabetes",
       "colesterol_alto",
       "doenca_cardiaca",
       "avc",
       "depressao",
       "outra_doenca_mental",
       "doenca_pulmonar_cronica",
       "cancer",
       "doenca_renal_cronica",
       "outra_doenca_cronica",
        "peso_nascer_inferior_2_5",
        "prematuro",
        "cesaria",     
       ]

df_grupo_maes = df_grupo_maes[colunas]

In [116]:
df_grupo_maes['pre_natal_adequado'].unique()

array(['Não', 'Sim'], dtype=object)

In [117]:
df_grupo_maes['imc_classificacao'].value_counts(dropna=False)

imc_classificacao
Normal             4204
Sobrepeso          3440
Obesidade          2110
None                393
Magreza             266
Obesidade Grave     162
Name: count, dtype: int64

In [118]:
df_grupo_maes.head()

,V0024,UPA_PNS,V00291,UF,regiao_metropolitana,capital_metropolitana,sexo,dia_nascimento,mes_nascimento,ano_nascimento,idade,estado_civil,UF_sigla,regiao_brasileira,raca,ano_nascimento_inferido,escolaridade,idade_ultimo_parto,parto_idade_avancada,filho,faixa_renda_per_capta,imc_classificacao,comorbidade,atividade_fisica,pre_natal_adequado,hipertensao,fumante_atual,diabetes,colesterol_alto,doenca_cardiaca,avc,depressao,outra_doenca_mental,doenca_pulmonar_cronica,cancer,doenca_renal_cronica,outra_doenca_cronica,peso_nascer_inferior_2_5,prematuro,cesaria
0,1110011,110000016,368.875166,11,Urbano,Capital,Feminino,22.0,11.0,1963.0,55.0,Casado,Rondônia,Norte,Branca,1963.0,Fundamental,24.0,0,1,<1 SM,Sobrepeso,Sim,Sim,Não,1,0,0,1,0,0,1,0,0,0,0,0,Não,Não,Não
1,1110011,110000016,614.791943,11,Urbano,Capital,Feminino,27.0,11.0,1973.0,45.0,Solteiro,Rondônia,Norte,Preta,1973.0,Médio,21.0,0,1,<1 SM,Obesidade,Não,Não,Não,0,0,0,0,0,0,0,0,0,0,0,0,Não,Não,Não
2,1110011,110000016,121.284625,11,Urbano,Capital,Feminino,30.0,7.0,1990.0,28.0,Solteiro,Rondônia,Norte,Parda,1990.0,NaN,28.0,0,1,<1 SM,Magreza,Não,Sim,Não,0,0,0,0,0,0,0,0,0,0,0,0,Não,Não,Não
3,1110011,110000034,149.846810,11,Urbano,Capital,Feminino,31.0,10.0,1985.0,33.0,Solteiro,Rondônia,Norte,Branca,1985.0,Pós-graduação,33.0,0,1,≥5 SM,Sobrepeso,Sim,Sim,Sim,0,0,0,0,0,0,1,0,0,0,0,0,Não,Sim,Sim
4,1110011,110000153,462.277154,11,Urbano,Capital,Feminino,17.0,5.0,1950.0,69.0,Casado,Rondônia,Norte,Parda,1950.0,NaN,32.0,0,1,<1 SM,Sobrepeso,Sim,Não,Não,1,1,0,0,0,0,0,0,0,0,0,0,Não,Não,Não

In [119]:
df_grupo_maes.to_csv('data/df_maes_grupo_2019.csv', index=False)
# df_grupo_criancas.to_csv('data/df_criancas_grupo_2019.csv', index=False)

In [120]:
df_grupo_maes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10575 entries, 0 to 10574
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   V0024                     10575 non-null  int64
 1   UPA_PNS                   10575 non-null  int64
 2   V00291                    10575 non-null  float64
 3   UF                        10575 non-null  int64
 4   regiao_metropolitana      10575 non-null  object
 5   capital_metropolitana     10575 non-null  object
 6   sexo                      10575 non-null  object
 7   dia_nascimento            10575 non-null  float64
 8   mes_nascimento            10575 non-null  float64
 9   ano_nascimento            10575 non-null  float64
 10  idade                     10575 non-null  float64
 11  estado_civil              10575 non-null  object
 12  UF_sigla                  10575 non-null  object
 13  regiao_brasileira         10575 non-null  object
 14  raca                      10575 non-null  object
 15  ano_nascimento_inferido   10575 non-null  float64
 16  escolaridade              9491 non-null   object
 17  idade_ultimo_parto        10575 non-null  float64
 18  parto_idade_avancada      10575 non-null  int64
 19  filho                     10575 non-null  int64
 20  faixa_renda_per_capta     10575 non-null  category
 21  imc_classificacao         10182 non-null  object
 22  comorbidade               10575 non-null  object
 23  atividade_fisica          10575 non-null  object
 24  pre_natal_adequado        10575 non-null  object
 25  hipertensao               10575 non-null  int64
 26  fumante_atual             10575 non-null  int64
 27  diabetes                  10575 non-null  int64
 28  colesterol_alto           10575 non-null  int64
 29  doenca_cardiaca           10575 non-null  int64
 30  avc                       10575 non-null  int64
 31  depressao                 10575 non-null  int64
 32  outra_doenca_mental       10575 non-null  int64
 33  doenca_pulmonar_cronica   10575 non-null  int64
 34  cancer                    10575 non-null  int64
 35  doenca_renal_cronica      10575 non-null  int64
 36  outra_doenca_cronica      10575 non-null  int64
 37  peso_nascer_inferior_2_5  10575 non-null  object
 38  prematuro                 10575 non-null  object
 39  cesaria                   10575 non-null  object
dtypes: category(1), float64(7), int64(17), object(15)
memory usage: 3.2+ MB

In [121]:
df_grupo_maes.regiao_brasileira.unique()

array(['Norte', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste'],
      dtype=object)

In [122]:
df_grupo_maes.regiao_metropolitana.unique()

array(['Urbano', 'Rural'], dtype=object)

In [123]:
df_grupo_maes.estado_civil.unique()

array(['Casado', 'Solteiro', 'Divorciado', 'Viúvo'], dtype=object)

In [124]:
df_grupo_maes.raca.unique()

array(['Branca', 'Preta', 'Parda', 'Amarela', 'Indígena'], dtype=object)

In [125]:
df_grupo_maes.escolaridade.unique()

array(['Fundamental', 'Médio', nan, 'Pós-graduação', 'Superior'],
      dtype=object)

In [126]:
df_grupo_maes.estado_civil.unique()

array(['Casado', 'Solteiro', 'Divorciado', 'Viúvo'], dtype=object)

In [128]:
1==1

True